services:
    phpbbmodders.oneclickban.listener:
        class: phpbbmodders\oneclickban\event\oneclickban_listener
        arguments:
            - @template
            - @user
            - @dbal.conn
            - @auth
            - @request
            - @cache.driver
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }
